# Ce workflow a été créé par : https://github.com/eloiJhn

# Ce workflow automatise le déploiement d'une application Android sur Firebase App Distribution. Lorsqu'un changement est poussé sur la branche principale (main), le workflow se déclenche.

# Il effectue les étapes suivantes :

# 1) Il commence par extraire le code du dépôt à l'aide de l'action actions/checkout@v3.
# 2) Il configure ensuite l'environnement d'exécution en installant .NET Core et Node.js.
# 3) Il installe les dépendances de travail de .NET nécessaires pour le développement d'applications Android.
# 4) Il restaure les dépendances du projet .NET à partir du fichier de solution.
# 5) Il compile le projet en utilisant la commande dotnet build, en utilisant une clé de signature Android stockée de manière sécurisée.
# 6) Il publie ensuite l'application Android, générant un fichier APK.
# 7) Il installe l'interface de ligne de commande Firebase (Firebase CLI).
# 8) Enfin, il déploie le fichier APK sur Firebase App Distribution, en le rendant accessible à un groupe de testeurs.

# L'environnement de construction et les secrets (comme les mots de passe de la clé de signature et le token Firebase) sont gérés de manière sécurisée par GitHub Actions.

name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '7.0.x'
  
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
   
    - name: Install .NET Workloads
      run: dotnet workload install maui-android

    - name: Install dependencies
      run: dotnet restore <YourSolutionPath> 
      # Remplacer <YourSolutionPath> par le chemin de votre solution. Exemple : DeployApp/DeployApp/DeployApp.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore <YourSolutionPath> 
      # Remplacer <YourSolutionPath> par le chemin de votre solution. Exemple : NameProject/DeployApp.sln
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/<YourKeystorePath>
        # Remplacer <YourKeystorePath> par le chemin de votre fichier keystore. Exemple : NameProject/my-release-key.keystore
        KEYSTORE_PASSWORD:  ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Publish
      run: dotnet publish <YourProjectPath> --framework net7.0-android --configuration Release --output ./publish/android
      # Remplacer <YourProjectPath> par le chemin de votre projet. Exemple : NameProject/DeployApp.csproj
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: appdistribution:distribute ./publish/android/<YourApkFile> --app <YourAppID>
        # Remplacer <YourApkFile> par le nom de votre fichier APK. Exemple : com.company.deployapp-Signed.apk
        # Remplacer <YourAppID> par l'ID de votre application.
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
