# This workflow was created by: https://github.com/eloiJhn

# This workflow automates the deployment of an Android application on Firebase App Distribution. When a change is pushed to the main branch, the workflow is triggered.

# It performs the following steps:

# 1) First, it extracts the code from the repository using the actions/checkout@v3 action.
# 2) He then configures the runtime environment by installing .NET Core and Node.js.
# 3) Installs the .NET working dependencies required for Android application development.
# 4) Restores .NET project dependencies from the solution file.
# 5) He compiles the project using the dotnet build command, using a securely stored Android signature key.
# 6) He then publishes the Android application, generating an APK file.
# 7) He installs the Firebase command-line interface (Firebase CLI).
# 8) Finally, he deploys the APK file on Firebase App Distribution, making it accessible to a group of testers.

# The build environment and secrets (such as signing key passwords and the Firebase token) are securely managed by GitHub Actions.

name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '7.0.x'
  
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
   
    - name: Install .NET Workloads
      run: dotnet workload install maui-android

    - name: Install dependencies
      run: dotnet restore <YourSolutionPath> 
      # Replace <YourSolutionPath> with your solution path. Example: DeployApp/DeployApp/DeployApp.sln

      
    - name: Build
      run: dotnet build --configuration Release --no-restore <YourSolutionPath> 
      # Remplacer <YourSolutionPath> par le chemin de votre solution. Exemple : NameProject/DeployApp.sln
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/<YourKeystorePath>
        # Replace <YourSolutionPath> with your solution path. Example: NameProject/DeployApp.sln
        KEYSTORE_PASSWORD:  ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Publish
      run: dotnet publish <YourProjectPath> --framework net7.0-android --configuration Release --output ./publish/android
      # Replace <YourProjectPath> with your project path. Example: NameProject/DeployApp.csproj
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: appdistribution:distribute ./publish/android/<YourApkFile> --app <YourAppID>
        # Replace <YourApkFile> with the name of your APK file. Example: com.company.deployapp-Signed.apk
        # Replace <YourAppID> with the ID of your application.
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
